export const CONTANTS = {
    GET_README : 'GET_README',
    GET_README_SUCCESS : 'GET_README_SUCCESS',
    GET_README_FAIL : 'GET_README_FAIL',
    SEARCH_REPO : 'SEARCH_REPO',
    SEARCH_REPO_SUCCESS : 'SEARCH_REPO_SUCCESS',
    SEARCH_REPO_FAIL : 'SEARCH_REPO_FAIL'
};