export const CONTANTS = {
    GET_README : 'GET_README',
    GET_README_SUCCESS : 'GET_README_SUCCESS',
    GET_README_FAIL : 'GET_README_FAIL',

    SEARCH_REPO : 'SEARCH_REPO',
    SEARCH_REPO_SUCCESS : 'SEARCH_REPO_SUCCESS',
    SEARCH_REPO_FAIL : 'SEARCH_REPO_FAIL',

    GET_REPO : 'GET_REPO',
    GET_REPO_SUCCESS : 'GET_REPO_SUCCESS',
    GET_REPO_FAIL : 'GET_REPO_FAIL',

    GET_USER : 'GET_USER',
    GET_USER_SUCCESS : 'GET_USER_SUCCESS',
    GET_USER_FAIL : 'GET_USER_FAIL',
};